# Generated by Django 3.2.6 on 2022-04-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors_name', models.CharField(max_length=300)),
                ('published_date', models.DateField(help_text='example: 2017-03-14')),
                ('isbn13_number', models.CharField(max_length=15)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('link_book_cover', models.URLField(blank=True, null=True)),
                ('language_book', models.CharField(max_length=40)),
            ],
        ),
    ]
